<cfquery name="GET_OPPORTUNITY_PLUSES" datasource="#dsn3#">
	SELECT
		PLUS_DATE,
		EMPLOYEE_ID,
		RECORD_EMP,
		COMMETHOD_ID,
		MAIL_SENDER,
		PLUS_CONTENT,
		OPP_PLUS_ID,
		MAIL_CC
	FROM
		OPPORTUNITIES_PLUS
	WHERE
		OPP_ID = #OPP_ID#
	ORDER BY
		RECORD_DATE DESC
</cfquery>
