<cfquery name="CONTROL_POS_PAYMENT" datasource="#dsn3#">
	SELECT 
		ORDER_CASH_POS.*,
		CREDIT_CARD_BANK_PAYMENTS.*
	FROM
		ORDERS,
		ORDER_CASH_POS,
		CREDIT_CARD_BANK_PAYMENTS
	WHERE
		ORDERS.ORDER_ID=ORDER_CASH_POS.ORDER_ID
		AND ORDER_CASH_POS.POS_ACTION_ID=CREDIT_CARD_BANK_PAYMENTS.CREDITCARD_PAYMENT_ID
		AND ORDERS.ORDER_ID = #attributes.order_id#
		AND (ORDER_CASH_POS.IS_CANCEL = 0  OR ORDER_CASH_POS.IS_CANCEL IS NULL)

	ORDER BY
		POS_ACTION_ID
</cfquery>
