<cfquery name="GET_PARTNER_COMPANY_AND_AUTHORITY" datasource="#dsn#">
	SELECT
		AUTHORITY.COMPANY_PARTNER_NAME,
		AUTHORITY.COMPANY_PARTNER_SURNAME
	FROM
		COMPANY,
		COMPANY_PARTNER,
		COMPANY_PARTNER AUTHORITY
	WHERE
		COMPANY_PARTNER.PARTNER_ID = #PARTNER_ID#
		AND
		COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID
		AND
		AUTHORITY.PARTNER_ID = COMPANY.PARTNER_ID
</cfquery>
