<cfquery name="GET_RIVAL_PREFERENCE_REASONS" datasource="#DSN#">
	SELECT
		PREFERENCE_REASON_ID,
		PREFERENCE_REASON
	FROM
		SETUP_RIVAL_PREFERENCE_REASONS
	ORDER BY
		PREFERENCE_REASON
</cfquery>
