<cfquery name="GET_STOCK_NAME" datasource="#DSN3#">
	SELECT
		PRODUCT.PRODUCT_NAME,
		STOCKS.PROPERTY,
		STOCKS.STOCK_CODE
	FROM
		PRODUCT,
		STOCKS
	WHERE
		STOCKS.STOCK_ID = #attributes.stock_id# AND
		PRODUCT.PRODUCT_ID = STOCKS.PRODUCT_ID
</cfquery>
