<cfquery name="GET_MEMBER_ANALYSIS_S" datasource="#dsn#">
	SELECT 
		ANALYSIS_ID,
		ANALYSIS_HEAD,
		ANALYSIS_PARTNERS	
	FROM 
		MEMBER_ANALYSIS,
		COMPANY,
		COMPANY_CAT
	WHERE
		MEMBER_ANALYSIS.IS_ACTIVE = 1 AND
		IS_PUBLISHED = 1 AND
		COMPANY.COMPANY_ID = #attributes.CPID# AND
		COMPANY_CAT.COMPANYCAT_ID = COMPANY.COMPANYCAT_ID		
</cfquery>

