<cfquery name="GET_COMPANY_PARTNER" datasource="#dsn#">
	SELECT
		COMPANY_PARTNER.*,
		COMPANY.MANAGER_PARTNER_ID,
		COMPANY.NICKNAME,
		COMPANY.FULLNAME
	FROM
		COMPANY_PARTNER,
		COMPANY
	WHERE
		COMPANY_PARTNER.PARTNER_ID = #PARTNER_ID#
		AND
		COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID
</cfquery>
