<cfquery name="GET_OFFER_PRODUCT" datasource="#dsn3#">
	SELECT 
		PS.*, 
		S.*, 
		P.*, 
		OP.PRICE AS OF_PRICE, 
		OP.QUANTITY AS OF_QUANTITY, 
		OP.PAY_METHOD_ID AS OF_PAYMETHOD  
	FROM 
		OFFER_PRODUCT OP,  
		PRICE_STANDART PS,
		STOCKS S,
		PRODUCT P
	WHERE 
		OP.OFFER_ID = #URL.OFFER_ID# 
		AND OP.STOCK_ID = S.STOCK_ID 
		AND	S.PRODUCT_ID = PS.PRODUCT_ID 
		AND S.PRODUCT_ID = P.PRODUCT_ID 
		AND	PS.PURCHASESALES = 1 
		AND	PS.PRICESTANDART_STATUS = 1
</cfquery>
