<cfquery name="GET_WORK_PARTNER" datasource="#DSN#">
	SELECT
		COMPANY_PARTNER.COMPANY_PARTNER_NAME,
		COMPANY_PARTNER.COMPANY_PARTNER_SURNAME,
		COMPANY_PARTNER.COMPANY_PARTNER_EMAIL,
		COMPANY.COMPANY_ID
	FROM
		COMPANY_PARTNER,
		COMPANY
	WHERE
		COMPANY_PARTNER.PARTNER_ID = <cfqueryparam cfsqltype="cf_sql_integer" value="#form.task_partner_id#"> AND
		COMPANY.COMPANY_ID = COMPANY_PARTNER.COMPANY_ID
</cfquery>
