<cfquery name="get_work" datasource="#dsn#">
	SELECT
		COUNT(WORK_ID) AS DURUM_SAYI,
		PROCESS_TYPE_ROWS.PROCESS_ROW_ID,
		PROCESS_TYPE_ROWS.STAGE,
		WORK_CURRENCY_ID 
	FROM 
		PRO_WORKS,
		PROCESS_TYPE_ROWS
	WHERE
		PRO_WORKS.WORK_STATUS = 1 AND
		PROCESS_TYPE_ROWS.PROCESS_ROW_ID = PRO_WORKS.WORK_CURRENCY_ID
	GROUP BY 
		PROCESS_TYPE_ROWS.PROCESS_ROW_ID,
		PROCESS_TYPE_ROWS.STAGE,
		PRO_WORKS.WORK_CURRENCY_ID
</cfquery>
